- platform: broadlink
  host: 192.168.10.141
  mac: 'c8:f7:42:16:7f:98'
  switches:
    # Mitsubishi Fan:
    mitsubishi_fan_swing:
      friendly_name: "Mitsubishi Fan Swing"
      command_on: 'JgCGAGk1DiYOJg4NDQ0NDQ0mDg0NDQ0mDiYODQ0mDg0NDQwnDiYODQ0mDiYODQ0mDg0NDQ0NDQ0NDQ0mDg0NDQ0NDSYODQ0NDQ0NDQ0NDQ0NDQ0NDSYOJg4NDQ0NJQ8NDQ0NDQ0lDyUPJQ8NDQ0NDQ0NDQ0NDQ0NDQwODQ0NDSUPJRALDiUPAA0FAAA'
      command_off: 'JgCGAGk1DiYOJg4NDQ0NDQ0mDg0NDQ0mDiYODQ0mDg0NDQwnDiYODQ0mDiYODQ0mDg0NDQ0NDQ0NDQ0mDg0NDQ0NDSYODQ0NDQ0NDQ0NDQ0NDQ0NDSYOJg4NDQ0NJQ8NDQ0NDQ0lDyUPJQ8NDQ0NDQ0NDQ0NDQ0NDQwODQ0NDSUPJRALDiUPAA0FAAA'
    mitsubishi_fan_natural_mode:
      friendly_name: "Mitsubishi Fan Natural Mode"
      command_on: 'JgCGAGwyDyUQJBAKDwwODA4lEAoPCxAkDyUQCg8lEAoPCxAkECQQChAkDyUQBxMlDwoPCxAKEAoPCxAjEQkRCREJESMRCREJEAoRCREJEQkRCREKECMRIxEJEAoRIxAKEQkRCRAkESMQChEjEAoQChEJEAoRCRAKEAoRChAJECQRCRAkECQQAA0FAAA='
      command_off: 'JgCGAGszDiYOJg4MDgwODA4mDgwODA4mDiYODA4mDgwODA4mDiYODA4mDiYODA4mDgwODA4MDgwODA4mDgwODA4MDiYODA4MDgwODA4MDgwODA4MDiYOJg4MDgwOJg4MDgwODA4mDgwOJg4MDgwODA4MDgwODA4MDgwODA4MDgwOJQ8MDiUPAA0FAAA='
    mute:
      friendly_name: "Mute"
      command_on: 'JgBQAJWUEBEQERAREBEQMhAyERAQERExEDIQMhAyEBIPEREQEBIPlRARERAQERAREDIREBAREBIPMhAyEDIQEg8RETERMRExERAREBEQEDIRAA0FAAAAAAAAAAA='
      command_off: 'JgBQAJWUEBEQERAREBEQMhAyERAQERExEDIQMhAyEBIPEREQEBIPlRARERAQERAREDIREBAREBIPMhAyEDIQEg8RETERMRExERAREBEQEDIRAA0FAAAAAAAAAAA='
    # Kangaroo Fan:
    kangaroo_fan_swing:
      friendly_name: "Kangaroo Fan Swing"
      command_on: 'JgDQACkOKg4OKCoPKA8OKBAnDykNKioODSkOAAELKw0rDgktKg0rDQ0qDioOJw8pKg4OKA8AAQspDikPDCspDioNDioNKg4oDykqDQ4qDgABCykOKQ4NKikPKBAMKQ4qDioPJyoODSoOAAELKBAoDw8oKg0oEAwrDSoPJxEnKQ8OKQ0AAQsqDykNDisnDykPDCsNKg0qDikqDgwqDwABCyoNKQ8NKSkPKQ4MKg8pDSsNKikODigPAAELKg4pDg4oKQ8pEAksDioOKA8pKQ8JLg0ADQUAAAAAAAAAAA=='
      command_off: 'JgDQACkOKg4OKCoPKA8OKBAnDykNKioODSkOAAELKw0rDgktKg0rDQ0qDioOJw8pKg4OKA8AAQspDikPDCspDioNDioNKg4oDykqDQ4qDgABCykOKQ4NKikPKBAMKQ4qDioPJyoODSoOAAELKBAoDw8oKg0oEAwrDSoPJxEnKQ8OKQ0AAQsqDykNDisnDykPDCsNKg0qDikqDgwqDwABCyoNKQ8NKSkPKQ4MKg8pDSsNKikODigPAAELKg4pDg4oKQ8pEAksDioOKA8pKQ8JLg0ADQUAAAAAAAAAAA=='
    kangaroo_fan_ion:
      friendly_name: "Kangaroo Fan Ion"
      command_on: 'JgCcACoOKg4OKCoOKg0OKQ8oDikqDg8oDikPAAEKKg4qDQ8oKg0qDQ4qDygPKCsMDykPKA8AAQoqDikNDykpDioNDygQJw8pKQ8NKQ4pDwABCisNKQ4OKSoNKw4OKA4pDikqDg8oDygOAAELKg0sDA8oKwwqDQ4qDygPKCoODigOKg4AAQoqDykNDikrDSoNDygOKQ8pKQ8NKQ4pDwANBQAAAAAAAAAAAAAAAA=='
      command_off: 'JgCcACoOKg4OKCoOKg0OKQ8oDikqDg8oDikPAAEKKg4qDQ8oKg0qDQ4qDygPKCsMDykPKA8AAQoqDikNDykpDioNDygQJw8pKQ8NKQ4pDwABCisNKQ4OKSoNKw4OKA4pDikqDg8oDygOAAELKg0sDA8oKwwqDQ4qDygPKCoODigOKg4AAQoqDykNDikrDSoNDygOKQ8pKQ8NKQ4pDwANBQAAAAAAAAAAAAAAAA=='
    kangaroo_fan_mist:
      friendly_name: "Kangaroo Fan Mist"
      command_on: 'JgDQACoNKg0PKCoOKg0OKQ4pKw0OKQ8oDikOAAELKg4pDg4pKw0qDQ8oDygqDg0qDikOKQ4AAQsrDCoODikpDioNDioOKSoNDikPKA4qDwABCikOKg0OKSoOKg0OKRAnKg4OKQ4pDygOAAELKg4pDg4pKg0rDQ4pDikrDQ0qDikPKA4AAQsqDSoODikqDSsMDioPKCoNDygOKQ8pDwABCSsNKg0PKCsNKQ4PKA8oKw0OKQ8oDygPAAEKKg4qDQ8oKg0rDQ4pDikqDQ4pDykPKA4ADQUAAAAAAAAAAA=='
      command_off: 'JgDQACoNKg0PKCoOKg0OKQ4pKw0OKQ8oDikOAAELKg4pDg4pKw0qDQ8oDygqDg0qDikOKQ4AAQsrDCoODikpDioNDioOKSoNDikPKA4qDwABCikOKg0OKSoOKg0OKRAnKg4OKQ4pDygOAAELKg4pDg4pKg0rDQ4pDikrDQ0qDikPKA4AAQsqDSoODikqDSsMDioPKCoNDygOKQ8pDwABCSsNKg0PKCsNKQ4PKA8oKw0OKQ8oDygPAAEKKg4qDQ8oKg0rDQ4pDikqDQ4pDykPKA4ADQUAAAAAAAAAAA=='
- platform: broadlink
  host: 192.168.10.144
  mac: 'c8:f7:42:16:81:cd'
  switches:
    #Hitachi Fan:
    hitachi_fan_swing:
      friendly_name: "Hitachi Fan Swing"
      command_on: 'JgBQAAABKZUTERM3ExISEhMSExITERM3EjgSExMRExISEhM3FBESEhM3EzcUNhM3FBETERQRExITERMSExETEhI4EzcTNxI4EwAFzQABKkkTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKZUTERM3ExISEhMSExITERM3EjgSExMRExISEhM3FBESEhM3EzcUNhM3FBETERQRExITERMSExETEhI4EzcTNxI4EwAFzQABKkkTAA0FAAAAAAAAAAA='
    hitachi_fan_natural_mode:
      friendly_name: "Hitachi Fan Natural Mode"
      command_on: 'JgBIAAABKpQTEhI3ExISExISExISEhM3EzcTEhMRFBETERQ2ExITERQ2EzcTEhM3ExITERMSExETEhMRFDYUERM3EjgTNxM3EgANBQ=='
      command_off: 'JgBIAAABKpQTEhI3ExISExISExISEhM3EzcTEhMRFBETERQ2ExITERQ2EzcTEhM3ExITERMSExETEhMRFDYUERM3EjgTNxM3EgANBQ=='
    hitachi_fan_night_mode:
      friendly_name: "Hitachi Fan Night Mode"
      command_on: 'JgBIAAABKpQUERM3ExEUERMSExETExI3EzcTERQRExEUERM3ExITERQ2FDYUNhQREzcVDxQRExITERQRExEUNhQREzcTNxU1FQANBQ=='
      command_off: 'JgBIAAABKpQUERM3ExEUERMSExETExI3EzcTERQRExEUERM3ExITERQ2FDYUNhQREzcVDxQRExITERQRExEUNhQREzcTNxU1FQANBQ=='
    hitachi_fan_night_mode_10h:
      friendly_name: "Hitachi Fan Night Mode 10h"
      command_on: 'JgBIAAABKpQUERM3ExEUERMSExETExI3EzcTERQRExEUERM3ExITERQ2FDYUNhQREzcVDxQRExITERQRExEUNhQREzcTNxU1FQANBQ=='
      command_off: 'JgBIAAABKpQUERM3ExEUERMSExETExI3EzcTERQRExEUERM3ExITERQ2FDYUNhQREzcVDxQRExITERQRExEUNhQREzcTNxU1FQANBQ=='
